import Head from "next/head";
import useSWR from "swr";
import { fetcher } from "../../utils/fetcher";
import { Header } from "../../components/header/Header";
import Link from "next/link";

const useUsers = () => {
  const { data, error } = useSWR(
    "https://jsonplaceholder.typicode.com/users",
    fetcher
  );
  return {
    data,
    error,
    isLoading: !data && !error,
    isEmpoty: data && data.length === 0,
  };
};

const UserCompornents =()=>{
  const { data, error, isLoading, isEmpoty } = useUsers();

  if (isLoading) {
    return <p>Loading...</p>;
  }
  if (error) {
    return <p>{error.message}</p>;
  }
  if (isEmpoty) {
    return <p>No users found</p>;
  }
  return(
    <ol>
    {data.map((user) => {
      return (
        <li key={user.id}>
          <Link href={`/users/${user.id}`}>
            <a>{`${user.name} (${user.email})`}</a>
          </Link>
        </li>
      );
    })}
  </ol>
  )
}

const Users = () => {
  
  //この上のif分の処理（エラー時の処理）の記述がないとswrは実行できない。mapが使えない。
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <UserCompornents />
    </div>
  );
};

export default Users;
