import Head from "next/head";
import styles from "../../../styles/Home.module.css";
import { Header } from "../../../components/Header";
import { UserComponente } from "../../../components/User";

const UsersId = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <UserComponente></UserComponente>
    </div>
  );
};

export default UsersId;
