import Head from "next/head";
import styles from "../../../styles/Home.module.css";
import { Header } from "../../../components/header/Header";
import { UserComponent } from "../../../components/users/User";
import { SWRConfig } from "swr";

export const getServerSideProps = async (ctx) => {
  const { id } = ctx.query;
  //ユーザーの情報を取得
  const USER_API_URL = `https://jsonplaceholder.typicode.com/users/${id}`;
  const user = await fetch(USER_API_URL);
  const userData = await user.json();
  //ユーザーの投稿の情報を取得
  const POSTS_API_URL = `https://jsonplaceholder.typicode.com/posts?userId=${userData.id}`;
  const posts = await fetch(POSTS_API_URL);
  const postsData = await posts.json();

  return {
    props: {
      fallback: {
        [USER_API_URL]: userData,
        // [POSTS_API_URL]: postsData,
      },
    },
  };
};
const UsersId = (props) => {
  const { fallback } = props;
  return (
    <SWRConfig className={styles.container} value={{ fallback }}>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <UserComponent></UserComponent>
    </SWRConfig>
  );
};

export default UsersId;

//SWRConfigをラップする形の書き方でも大丈夫
//全部やるのではなくてところどころで取り入れる
//インタラクティブ性があまり良くない。
//画面だけの遷移は
