import Head from "next/head";
import styles from "../../../styles/Home.module.css";
import { Header } from "../../../components/header/Header";
import { UserComponent } from "../../../components/users/User";
import { SWRConfig } from "swr";

export const getServerSideProps = async (ctx) => {
  const { id } = ctx.query;
  const API_URL = `https://jsonplaceholder.typicode.com/users/${id}`;
  const user = await fetch(API_URL);
  const userData = await user.json();

  return {
    props: {
      fallback: {
        [API_URL]: userData,
      },
    },
  };
};
const UsersId = (props) => {
  const { fallback } = props;
  return (
    <SWRConfig className={styles.container} value={{fallback}}>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <UserComponent></UserComponent>
    </SWRConfig>
  );
};

export default UsersId;

//SWRConfigをラップする形の書き方でも大丈夫