import Head from "next/head";
import styles from "../../../styles/Home.module.css";
import { Footer } from "../../../components/Footer";
import { Post } from "../../../components/Post";
import { Main } from "../../../components/Main";
import { usePost } from "../../../hooks/usePost";

const PostId = () => {
  const { post } = usePost();
  return (
    <div className={styles.container}>
      <Head>
        <title>{post?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main title="Index"></Main>
      <Post></Post>
      <Footer></Footer>
    </div>
  );
};

export default PostId;
