import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Footer } from "../components/footer/Footer";
import { Main } from "../components/main/Main";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Learn Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main title="Index"></Main>
      <div className={styles.main}>
        <h1 className="font-bold text-3xl">Learn Next.js</h1>
        <p>JSONPlaceholder</p>
      </div>
      <Footer></Footer>
    </div>
  );
}
