import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Footer } from "../components/Footer";
import { Main } from "../components/Main";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Learn Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main title="Index"></Main>
      <div className={styles.main}>
        <h1>Learn Next.js</h1>
        <p>JSONPlaceholder</p>
      </div>
    </div>
  );
}
