import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { Footer } from "../../components/Footer";
import { Main } from "../../components/Main";
import { useRouter } from "next/router";


const PostId=()=> {
  const router = useRouter()
  console.log(router.query.id);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main title="Index"></Main>
      <div className={styles.main}>{router.query.id}</div>
      <Footer></Footer>
    </div>
  );
}

export default PostId