import Head from "next/head";
import styles from "../../../styles/Home.module.css";
import { useRouter } from "next/router";
import { Header } from "../../../components/Header";
import { CommentComponente } from "../../../components/Comment";

const CommentsId = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <CommentComponente />
    </div>
  );
};

export default CommentsId;
