import Head from "next/head";
import { SWRConfig } from "swr";
import { Header } from "../../components/header/Header";
import { UsersComponent } from "../../components/users/Users";

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve));

export const getServerSideProps = async () => {
  //ユーザーズの情報を取得
  const USERS_API_URL = `https://jsonplaceholder.typicode.com/users`;
  const users = await fetch(USERS_API_URL);
  const usersData = await users.json();
  await sleep(2000);
  return {
    props: {
      fallback: {
        [USERS_API_URL]: usersData,
        // [POSTS_API_URL]: postsData,
      },
    },
  };
};
const Users = (props) => {
  const { fallback } = props;

  //この上のif分の処理（エラー時の処理）の記述がないとswrは実行できない。mapが使えない。
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SWRConfig value={{ fallback }}>
        <Header />
        <UsersComponent />
      </SWRConfig>
    </div>
  );
};

export default Users;
