import Head from "next/head";
import { Header } from "../../components/Header";
import { CommentsCompornents } from "../../components/Comments";

const Comments = () => {
  //この上のif分の処理（エラー時の処理）の記述がないとswrは実行できない。mapが使えない。
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <CommentsCompornents />
    </div>
  );
};

export default Comments;
